### PR TITLE
Fix CI error : error[E0308]: mismatched types

### PR DESCRIPTION
**Pull request by Xynnn007**
```
error[E0308]: mismatched types
   --> /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/ttrpc-codegen-0.2.2/src/lib.rs:128:28
    |
128 |                 .customize(self.rust_protobuf_customize.clone())
    |                  --------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `protobuf_codegen_pure3::Customize`, found struct `protobuf_codegen::Customize`
    |                  |
    |                  arguments to this function are incorrect
    |
    = note: struct `protobuf_codegen::Customize` and struct `protobuf_codegen_pure3::Customize` have similar names, but are actually distinct types
note: struct `protobuf_codegen::Customize` is defined in crate `protobuf_codegen`
   --> /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-codegen-2.28.0/src/customize.rs:9:1
    |
9   | pub struct Customize {
    | ^^^^^^^^^^^^^^^^^^^^
note: struct `protobuf_codegen_pure3::Customize` is defined in crate `protobuf_codegen3`
   --> /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-codegen3-2.28.2/src/customize.rs:9:1
    |
9   | pub struct Customize {
    | ^^^^^^^^^^^^^^^^^^^^
note: associated function defined here
   --> /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-codegen-pure3-2.28.2/src/lib.rs:122:12
    |
122 |     pub fn customize(&mut self, customize: Customize) -> &mut Self {
    |            ^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `ttrpc-codegen` due to previous error
warning: build failed, waiting for other jobs to finish...
make[2]: *** [src/attesters/sev/CMakeFiles/ttrpc_lib] Error 101
src/attesters/sev/CMakeFiles/ttrpc_lib.dir/build.make:57: recipe for target 'src/attesters/sev/CMakeFiles/ttrpc_lib' failed
make[2]: Leaving directory '/__w/attestation-agent/attestation-agent/rats-tls/build'
CMakeFiles/Makefile2:416: recipe for target 'src/attesters/sev/CMakeFiles/ttrpc_lib.dir/all' failed
make[1]: Leaving directory '/__w/attestation-agent/attestation-agent/rats-tls/build'
make[1]: *** [src/attesters/sev/CMakeFiles/ttrpc_lib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/__w/attestation-agent/attestation-agent/rats-tls/build'
```

- update rats-tls version in CI: Old version fails to build due to the dependency `protobuf-codegen-pure3` changes its api but does not update the major version.
- delete Cargo.lock in lib

### CODE REVIEW

**Review by fitzthum — APPROVED** [review]
LGTM

**Comment by jialez0** [comment]
@Xynnn007 We only need to change the OS version to 20.04 to pass CI without changing the rats-tls version. For EAA KBC, we'd better not modify the current version of rats-tls, because this is the most appropriate version that can support EAA KBC running at present.

**Comment by jialez0** [comment]
@Xynnn007 Now we do not need to make these changes, and the CI can also pass normally, so this PR can be closed?

**Comment by Xynnn007** [comment]
No need from this PR

**Pull request closed without merging**
